#Makefile generated by amake
#On Wed Jun 10 17:09:24 2020
#To print amake help use 'amake --help'.
CC=gcc
CPPC=g++
LINK=g++
SRCDIR=src
OBJDIR=obj
FLAGS=-g -Wall -std=c++11 -pthread -I/usr/include/ncursesw 
LIBS=-lncursesw 
OBJS=$(OBJDIR)/wdisplay.o $(OBJDIR)/mhw_lookup.o $(OBJDIR)/main.o $(OBJDIR)/utils.o $(OBJDIR)/ui.o $(OBJDIR)/fdisplay.o $(OBJDIR)/memory.o $(OBJDIR)/patterns.o 
EXEC=linux-hunter
DATE=$(shell date +"%Y-%m-%d")

$(EXEC) : $(OBJS)
	$(LINK) $(OBJS) -o $(EXEC) $(FLAGS) $(LIBS)

$(OBJDIR)/wdisplay.o: src/display/wdisplay.cpp src/display/wdisplay.h src/display/vbrush.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/display/wdisplay.cpp -c -o $@

$(OBJDIR)/mhw_lookup.o: src/parsing/mhw_lookup.cpp src/parsing/mhw_lookup.h src/parsing/memory.h \
 src/parsing/patterns.h src/display/ui.h src/timer.h src/display/vbrush.h \
 src/parsing/mhw_lookup_monster.h src/parsing/offsets.h src/data/data.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/parsing/mhw_lookup.cpp -c -o $@

$(OBJDIR)/main.o: src/main.cpp src/parsing/memory.h src/parsing/patterns.h src/display/ui.h src/timer.h \
 src/display/vbrush.h src/display/wdisplay.h src/display/fdisplay.h src/events.h src/parsing/mhw_lookup.h \
 src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/main.cpp -c -o $@

$(OBJDIR)/utils.o: src/utils.cpp src/utils.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/utils.cpp -c -o $@

$(OBJDIR)/ui.o: src/display/ui.cpp src/display/ui.h src/timer.h src/display/vbrush.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/display/ui.cpp -c -o $@

$(OBJDIR)/fdisplay.o: src/display/fdisplay.cpp src/display/fdisplay.h src/display/vbrush.h \
 src/hashtext_fmt.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/display/fdisplay.cpp -c -o $@

$(OBJDIR)/memory.o: src/parsing/memory.cpp src/parsing/memory.h src/parsing/patterns.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/parsing/memory.cpp -c -o $@

$(OBJDIR)/patterns.o: src/parsing/patterns.cpp src/parsing/patterns.h $(OBJDIR)/__setup_obj_dir
	$(CPPC) $(FLAGS) src/parsing/patterns.cpp -c -o $@

$(OBJDIR)/__setup_obj_dir :
	mkdir -p $(OBJDIR)
	touch $(OBJDIR)/__setup_obj_dir

.PHONY: clean bzip release

clean :
	rm -rf $(OBJDIR)/*.o
	rm -rf $(EXEC)

bzip :
	tar -cvf "$(DATE).$(EXEC).tar" $(SRCDIR)/* Makefile
	bzip2 "$(DATE).$(EXEC).tar"

release : FLAGS +=-O3 -D_RELEASE
release : $(EXEC)

